### ISSUE TITLE
[Dash] DOCs can see dashboard with statistics

### ISSUE THREAD

**Issue by gabrielsaruhashi** [Ameelio/connect-doc-client#17]
**Is your feature request related to a problem? Please describe.**
DOC should be able to see an overview of the calls/metrics/etc
This will involve some refactoring of how calls are currently being loaded upon initialization.

**Describe the solution you'd like**
Fetch calls and display info on the main dash.
It's fine to adjust the design to match antd's statistics component (https://ant.design/components/statistic/).
@gabrielsaruhashi kicked off the design, but still needs styling + populating data

**To-Do**

- [ ] Should be able to see the number of live calls happening
- [ ] Should be able to see the number of calls this week
- [ ] Should be able a chart with the number of live visitations
- [ ] Should be able to see the average call rating
- [ ] Should be able to see what % of incarcerated people in that facility have participated in the program

**Additional context**

![image](https://user-images.githubusercontent.com/12942772/106466428-11104a00-647a-11eb-9da7-f7375040aa91.png)

**Out of scope**
View details
Changing date range of data view
Changing facility
