### ISSUE TITLE
[Live Calls] DOCs can monitor the chat for live calls

### ISSUE THREAD

**Issue by gabrielsaruhashi** [Ameelio/connect-doc-client#28]
## Is your feature request related to a problem? Please describe.
Currently, DOCs don't have a way to monitor the live chat.

## Describe the solution you'd like
DOCs can open the chat sider (similar to inc people interface) by using the action toggle on the top right corner of the call frame
![image](https://user-images.githubusercontent.com/12942772/108098462-297b8980-7062-11eb-8afb-a7f80af23c15.png)

## To-Dos
- [x] DOC receives text events
- [x] DOC can view chat message and metadata (timestamp, sender)
- [ ] DOC can switch between live chats by selecting the dropdow
- [ ] When users lock the call or changes to a single page, the active chat message is automatically updated
- [x] Users can also select "see chat message") as an extra option on the VideoOverlay commands

## Suggested Implementation
- Add the text message listener to the VideoChat component. You can see an implementation example on the [pathways client](https://github.com/Ameelio/pathways-client/)
- There's already a messages array on the BaseCall object, so I'd just add a reducer "ADD_MESSAGE" to the CallSlice to add the new message to the array
- Upon receiving a message event, you trigger the action creator
